version: 2
jobs:
  cljs:
    docker: 
      - image: circleci/clojure:lein-2.8.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: ./node_modules/.bin/shadow-cljs compile test-ci
      - run: karma start --single-run
workflows:
  version: 2
  fullstack:
    jobs:
      - cljs

